version: '3'
services:
  nydatapostgresdb:
    image: postgres:13
    container_name: ny_datapgdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./my_taxi_data:/var/lib/postgresql/data:rw"
    ports:
      - "5435:5432"

  nydatapgadmin:
    image: dpage/pgadmin4
    container_name: ny_datapgad
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8082:80"

  magic:
    image: mageai/mageai:latest
    container_name: datatalks-mage
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ~/datatalks/mage_orchestration/Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src
      - ~/datatalks/infra/keys/gcp_creds.json:/home/src/gcp_creds.json
    restart: on-failure:5